project:
  type: website
  output-dir: docs
  preview:
    port: 8000

bibliography: vaximm.bib

website:
  navbar:
    # background: dark
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Technology"
        href: technology.qmd
      - text: "Pipeline"
        href: pipeline.qmd
      - text: "About"
        href: about.qmd
      - text: "News"
        href: news.qmd
  page-footer:
    left:
      - text: "<i class=\"bi bi-geo-alt\"></i> VAXIMM AG<br>Hochbergerstrasse 60c, CH-4057 Basel, Switzerland"
    right:
      - text: "<i class=\"bi bi-telephone\"></i> +41 41 725 08 00<br><i class=\"bi bi-envelope\"></i> <a href='mailto:group@osr-holdings.com'>group@osr-holdings.com</a>"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Information** - This is a rudimentary draft version of the new VAXIMM website"
    type: primary
    position: below-navbar

format:
  html:
    theme: minty
    citations-hover: false
    css: custom.css
    include-in-header:
      - text: |
          <script src="animations.js" defer></script>